// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantityMeasurementRepository.EFCore;

#nullable disable

namespace QuantityMeasurement.Repository.Migrations
{
    [DbContext(typeof(QuantityMeasurementDbContext))]
    [Migration("20260421114948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementModel.Entities.QuantityMeasurementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("ResultMeasurementType")
                        .HasColumnType("text")
                        .HasColumnName("result_measurement_type");

                    b.Property<string>("ResultString")
                        .HasColumnType("text")
                        .HasColumnName("result_string");

                    b.Property<string>("ResultUnit")
                        .HasColumnType("text")
                        .HasColumnName("result_unit");

                    b.Property<double>("ResultValue")
                        .HasColumnType("double precision")
                        .HasColumnName("result_value");

                    b.Property<string>("ThatMeasurementType")
                        .HasColumnType("text")
                        .HasColumnName("that_measurement_type");

                    b.Property<string>("ThatUnit")
                        .HasColumnType("text")
                        .HasColumnName("that_unit");

                    b.Property<double>("ThatValue")
                        .HasColumnType("double precision")
                        .HasColumnName("that_value");

                    b.Property<string>("ThisMeasurementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("this_measurement_type");

                    b.Property<string>("ThisUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("this_unit");

                    b.Property<double>("ThisValue")
                        .HasColumnType("double precision")
                        .HasColumnName("this_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("Operation")
                        .HasDatabaseName("idx_operation");

                    b.HasIndex("ThisMeasurementType")
                        .HasDatabaseName("idx_measurement_type");

                    b.ToTable("QuantityMeasurements", (string)null);
                });

            modelBuilder.Entity("QuantityMeasurementModel.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
