// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementRepository.EFCore;

#nullable disable

namespace QuantityMeasurementRepository.Migrations
{
    [DbContext(typeof(QuantityMeasurementDbContext))]
    partial class QuantityMeasurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementModel.Entities.QuantityMeasurementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsError")
                        .HasColumnType("bit")
                        .HasColumnName("is_error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("operation");

                    b.Property<string>("ResultMeasurementType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_measurement_type");

                    b.Property<string>("ResultString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_string");

                    b.Property<string>("ResultUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_unit");

                    b.Property<double>("ResultValue")
                        .HasColumnType("float")
                        .HasColumnName("result_value");

                    b.Property<string>("ThatMeasurementType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("that_measurement_type");

                    b.Property<string>("ThatUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("that_unit");

                    b.Property<double>("ThatValue")
                        .HasColumnType("float")
                        .HasColumnName("that_value");

                    b.Property<string>("ThisMeasurementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("this_measurement_type");

                    b.Property<string>("ThisUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("this_unit");

                    b.Property<double>("ThisValue")
                        .HasColumnType("float")
                        .HasColumnName("this_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("Operation")
                        .HasDatabaseName("idx_operation");

                    b.HasIndex("ThisMeasurementType")
                        .HasDatabaseName("idx_measurement_type");

                    b.ToTable("QuantityMeasurements", (string)null);
                });

            modelBuilder.Entity("QuantityMeasurementModel.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
